# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20160830_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_list',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
